## Download data

In [2]:
import pandas as pd

In [ ]:
# Carga los archivos de dos sucursales en dos dataframes
df_del = pd.read_csv('../ventas_DEL.csv')
df_pal = pd.read_csv('../ventas_PAL.csv')

#### Explora la Sucursal 1

In [ ]:
df_del.head()

,Invoice No,Date,Line,Product Code,Invoice Quantity,Unit Cost,Net Unit Price,Price List,Price Limit,Price Std,Category Name,Total
0,DEL1000,12/05/2025,10,PLY-680,2,11.45,21.20,23.32,20.14,21.20,Plywood,42.40
1,DEL1001,17/08/2025,10,CEM-425,1,23.54,34.87,38.36,33.13,34.87,Cemento,34.87
2,DEL1001,17/08/2025,20,PLY-994,1,10.94,19.58,21.54,18.60,19.58,Plywood,19.58
3,DEL1001,17/08/2025,30,TUB-134,2,33.42,58.77,64.65,55.83,58.77,Tuberías,117.54
4,DEL1002,23/06/2026,10,PIN-721,3,22.66,32.27,35.50,30.66,32.27,Pinturas,96.81

In [13]:
df_del.info()

<class 'pandas.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Invoice No        522 non-null    str
 1   Date              522 non-null    str
 2   Line              522 non-null    int64
 3   Product Code      522 non-null    str
 4   Invoice Quantity  522 non-null    int64
 5   Unit Cost         522 non-null    float64
 6   Net Unit Price    522 non-null    float64
 7   Price List        522 non-null    float64
 8   Price Limit       522 non-null    float64
 9   Price Std         522 non-null    float64
 10  Category Name     522 non-null    str
 11  Total             522 non-null    float64
dtypes: float64(6), int64(2), str(4)
memory usage: 49.1 KB

In [12]:
print("Número de filas y columnas en df_del:", df_del.shape)

Número de filas y columnas en df_del: (522, 12)

#### Exlora la Sucursal 2

In [8]:
df_pal.head()

,Invoice No,Date,Line,Product Code,Invoice Quantity,Unit Cost,Net Unit Price,Price List,Price Limit,Price Std,Category Name,Total
0,PAL1000,25/04/2025,10,PLY-718,4,21.15,31.55,34.71,29.97,31.55,Plywood,126.20
1,PAL1001,24/02/2025,10,PIN-832,5,21.61,28.37,31.21,26.95,28.37,Pinturas,141.85
2,PAL1001,24/02/2025,20,CEM-403,5,29.33,38.19,42.01,36.28,38.19,Cemento,190.95
3,PAL1001,24/02/2025,30,SEG-800,4,27.31,46.34,50.97,44.02,46.34,Seguridad,185.36
4,PAL1001,24/02/2025,40,PIN-202,5,7.28,12.43,13.67,11.81,12.43,Pinturas,62.15

In [9]:
df_pal.info()

<class 'pandas.DataFrame'>
RangeIndex: 487 entries, 0 to 486
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Invoice No        487 non-null    str
 1   Date              487 non-null    str
 2   Line              487 non-null    int64
 3   Product Code      487 non-null    str
 4   Invoice Quantity  487 non-null    int64
 5   Unit Cost         487 non-null    float64
 6   Net Unit Price    487 non-null    float64
 7   Price List        487 non-null    float64
 8   Price Limit       487 non-null    float64
 9   Price Std         487 non-null    float64
 10  Category Name     487 non-null    str
 11  Total             487 non-null    float64
dtypes: float64(6), int64(2), str(4)
memory usage: 45.8 KB

In [11]:
print("Número de filas y columnas en df_pal:", df_pal.shape)

Número de filas y columnas en df_pal: (487, 12)